/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javarmi.conta_bancaria.gui;

import javarmi.conta_bancaria.impl.CliImpl;

/**
 *
 * @author Lucas
 */
public class OpcoesTransferencias extends javax.swing.JFrame {

    CliImpl cliImpl;
    
    /**
     * Creates new form OpcoesTransferencia
     * @param cli
     */
    public OpcoesTransferencias(CliImpl cli)
    {
        initComponents();
        cliImpl = cli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        paraContaCorrente = new javax.swing.JButton();
        paraPoupanca = new javax.swing.JButton();
        doc = new javax.swing.JButton();
        ted = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Painel de transferências");

        paraContaCorrente.setText("Para conta-corrente");
        paraContaCorrente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paraContaCorrenteActionPerformed(evt);
            }
        });

        paraPoupanca.setText("Para poupança");
        paraPoupanca.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paraPoupancaActionPerformed(evt);
            }
        });

        doc.setText("DOC");
        doc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                docActionPerformed(evt);
            }
        });

        ted.setText("TED");
        ted.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tedActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paraContaCorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paraPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(ted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paraContaCorrente)
                .addGap(11, 11, 11)
                .addComponent(paraPoupanca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tedActionPerformed
    {//GEN-HEADEREND:event_tedActionPerformed
        new TED(cliImpl).setVisible(true);
    }//GEN-LAST:event_tedActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_voltarActionPerformed
    {//GEN-HEADEREND:event_voltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void paraContaCorrenteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paraContaCorrenteActionPerformed
    {//GEN-HEADEREND:event_paraContaCorrenteActionPerformed
        new ParaCorrente(cliImpl).setVisible(true);
    }//GEN-LAST:event_paraContaCorrenteActionPerformed

    private void paraPoupancaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paraPoupancaActionPerformed
    {//GEN-HEADEREND:event_paraPoupancaActionPerformed
        new ParaPoupanca(cliImpl).setVisible(true);
    }//GEN-LAST:event_paraPoupancaActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_docActionPerformed
    {//GEN-HEADEREND:event_docActionPerformed
        new DOC(cliImpl).setVisible(true);
    }//GEN-LAST:event_docActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doc;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paraContaCorrente;
    private javax.swing.JButton paraPoupanca;
    private javax.swing.JButton ted;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
