/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javarmi.conta_bancaria.gui;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javarmi.conta_bancaria.impl.CliImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class OpcoesOperacoes extends javax.swing.JFrame {

    CliImpl cliImpl;
    
    /**
     * Creates new form OpcoesTransferencia
     * @param cli
     */
    public OpcoesOperacoes(CliImpl cli)
    {
        initComponents();
        cliImpl = cli;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        consultarSaldo = new javax.swing.JButton();
        depositar = new javax.swing.JButton();
        sacar = new javax.swing.JButton();
        transferencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        consultarSaldo.setText("Consultar Saldo");
        consultarSaldo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consultarSaldoActionPerformed(evt);
            }
        });

        depositar.setText("Depositar");
        depositar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                depositarActionPerformed(evt);
            }
        });

        sacar.setText("Sacar");
        sacar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sacarActionPerformed(evt);
            }
        });

        transferencia.setText("Transferência");
        transferencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                transferenciaActionPerformed(evt);
            }
        });

        jLabel1.setText("Painel de operações");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consultarSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sacar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sair)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarSaldoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consultarSaldoActionPerformed
    {//GEN-HEADEREND:event_consultarSaldoActionPerformed
        boolean ret = false;
        new ConsultarSaldo(cliImpl).setVisible(true);
    }//GEN-LAST:event_consultarSaldoActionPerformed

    private void depositarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_depositarActionPerformed
    {//GEN-HEADEREND:event_depositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositarActionPerformed

    private void transferenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_transferenciaActionPerformed
    {//GEN-HEADEREND:event_transferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferenciaActionPerformed

    private void sacarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sacarActionPerformed
    {//GEN-HEADEREND:event_sacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sacarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sairActionPerformed
    {//GEN-HEADEREND:event_sairActionPerformed
        String msg = "Obrigado por utilizar nosso sistema. Volte sempre!";
        JOptionPane.showMessageDialog(null, msg);
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarSaldo;
    private javax.swing.JButton depositar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sacar;
    private javax.swing.JButton sair;
    private javax.swing.JButton transferencia;
    // End of variables declaration//GEN-END:variables
}
